#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 16 18:28:52 2018

@author: hunterstabler
"""

"""
SCRIPT:  text-to-audio.py
AUTHOR:  Brendan Harmon <brendan.harmon@gmail.com>
PURPOSE: Open educational materials for a seminar on digital culture
LICENSE: GNU General Public License v2
DEPENDENCIES: playsound and gTTs
"""

# import libraries
from playsound import playsound
from gtts import gTTS

# text to speech
tts = gTTS(text="I am google hear me roar. robots don't pee on the floor", lang="en")

# write audio file
tts.save("robot.mp3")

# play audio file
playsound("robot.mp3")